import { NextResponse } from "next/server"
import { getServerSession } from "next-auth/next"
import { authOptions } from "@/lib/auth"
import { prisma } from "@/lib/prisma"
import * as XLSX from "xlsx"
import { jsPDF } from "jspdf"
import autoTable from "jspdf-autotable"

export async function GET(
  req: Request,
  { params }: { params: { id: string } }
) {
  const session = await getServerSession(authOptions)
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  const rosterId = params.id
  const { searchParams } = new URL(req.url)
  const format = searchParams.get("format") || "csv"

  if (!["csv", "xlsx", "pdf"].includes(format)) {
    return NextResponse.json({ error: "Invalid format. Use csv, xlsx, or pdf" }, { status: 400 })
  }

  const roster = await prisma.roster.findUnique({
    where: { id: rosterId },
    include: {
      weeks: {
        orderBy: { startDate: "asc" },
        include: {
          assignments: {
            include: {
              employee: { select: { initials: true, name: true } },
              shiftType: { select: { id: true, name: true, code: true, startTime: true } },
            },
          },
        },
      },
    },
  })

  if (!roster) {
    return NextResponse.json({ error: "Roster not found" }, { status: 404 })
  }

  // Get all shift types in order
  const shiftTypes = await prisma.shiftType.findMany({
    orderBy: { sortOrder: "asc" },
  })

  // Build data matrix: rows = weeks, cols = shift types, values = employee initials
  const rows = roster.weeks.map((week) => {
    const row: Record<string, string> = { Week: week.weekLabel }
    for (const st of shiftTypes) {
      const assignment = week.assignments.find((a) => a.shiftTypeId === st.id)
      row[st.name] = assignment?.employee?.initials || ""
    }
    return row
  })

  const fileName = `${roster.name.replace(/\s+/g, "_")}_${roster.year}_${roster.month}`

  if (format === "csv") {
    const headers = ["Week", ...shiftTypes.map((st) => st.name)]
    const csvRows = rows.map((row) =>
      headers.map((h) => `"${(row[h] || "").replace(/"/g, '""')}"`).join(",")
    )
    const csvContent = "\uFEFF" + [headers.join(","), ...csvRows].join("\n")

    return new NextResponse(csvContent, {
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="${fileName}.csv"`,
      },
    })
  }

  if (format === "xlsx") {
    const headers = ["Week", ...shiftTypes.map((st) => `${st.name}\n${st.startTime}`)]
    const data = rows.map((row) => [row.Week, ...shiftTypes.map((st) => row[st.name] || "")])

    const ws = XLSX.utils.aoa_to_sheet([headers, ...data])
    const wb = XLSX.utils.book_new()
    XLSX.utils.book_append_sheet(wb, ws, "Roster")

    // Set column widths
    const wscols = [{ wch: 12 }, ...shiftTypes.map(() => ({ wch: 18 }))]
    ws["!cols"] = wscols

    const buf = XLSX.write(wb, { type: "buffer", bookType: "xlsx" })

    return new NextResponse(buf, {
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "Content-Disposition": `attachment; filename="${fileName}.xlsx"`,
      },
    })
  }

  if (format === "pdf") {
    const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" })

    // Title
    doc.setFontSize(18)
    doc.setTextColor(15, 23, 42)
    doc.text("AXIOM - Duty Roster", 14, 20)

    doc.setFontSize(12)
    doc.setTextColor(100, 116, 139)
    doc.text(`${roster.name} - ${roster.month}/${roster.year}`, 14, 28)
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 34)

    const headers = ["Week", ...shiftTypes.map((st) => `${st.name} (${st.startTime})`)]
    const body = rows.map((row) => [
      row.Week,
      ...shiftTypes.map((st) => row[st.name] || "-"),
    ])

    autoTable(doc, {
      head: [headers],
      body,
      startY: 40,
      styles: {
        fontSize: 8,
        cellPadding: 2,
        overflow: "linebreak",
      },
      headStyles: {
        fillColor: [15, 23, 42],
        textColor: [255, 255, 255],
        fontSize: 8,
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252],
      },
      didDrawPage: (data) => {
        doc.setFontSize(8)
        doc.setTextColor(150, 150, 150)
        doc.text(
          "Generated by AXIOM - Taylor's ICT Service Desk",
          data.settings.margin.left,
          doc.internal.pageSize.height - 10
        )
      },
    })

    const pdfBytes = doc.output("arraybuffer")
    return new NextResponse(pdfBytes, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${fileName}.pdf"`,
      },
    })
  }

  return NextResponse.json({ error: "Unsupported format" }, { status: 400 })
}
